config/routes.rb
# -*- encoding : utf-8 -*-
Mysenso::Application.routes.draw do

  resource :user do
    resource :avatar do
      collection do
        get 'index'
        put 'update_crop'
      end
    end
  end

  resources :references, :only => [:destroy] do
    collection do
      get 'index'
    end
    member do
      put 'accept'
    end
  end

  resources :private_messages, :except => [:edit, :update] do
 
    collection do
      get 'received' => 'private_messages#index'
      get 'sent' => 'private_messages#index', :defaults => { :type => :sent }
      post 'destroy_multiple'
      post 'mark_as_read_multiple'
    end
    
  end

  resources :avatars

  resources :albums do
    resources :photos
    
    collection do
      get 'manage'
    end
    
    member do
      get 'manage', :action => 'manage_photos'
    end
  end

  devise_for :user, :path_prefix => 'd' do
    root :to => "home#index"
  end

  resources :users, :except => [:update, :show] do
    collection do
      get 'search'
      get 'search_companies'
      post 'index'
    end
    resource :private_message, :only => [:new]
    resources :references, :only => [:new, :create]
    resources :albums, :only => [:index]
  end
  get '/users/:id' => 'users#show', :as => 'user'
  put '/users/:id' => 'users#update', :as => 'user'

  root :to => "home#index"

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes 

  # Common fields
  field :first_name
  field :last_name
  field :login
  field :phone_number, :type => Integer
  field :region
  field :webpage
  field :courses
  field :gadu_gadu, :type => Integer
  field :skype
  field :achievements
  field :profile_completed, :type => Boolean, :default => false
  field :avatar
  field :city

  # Profile fields
  field :gender
  field :birth_date, :type => Date
  field :height, :type => Integer
  field :weight, :type => Integer
  field :bust, :type => Integer
  field :waist, :type => Integer
  field :hips, :type => Integer
  field :panties
  field :dress
  field :shoes, :type => Integer
  field :pants, :type => Integer
  field :neck, :type => Integer
  field :preferable_region
  field :about

  # Company fields
  field :nip, :type => Integer
  field :regon, :type => Integer
  field :postcode
  field :street
  field :company_name
  field :landline_number, :type => Integer
  field :fax_number, :type => Integer
  field :description
  field :company, :type => Boolean, :default => false


  key :login


  # Devise configuration
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

 
  # Accessible attributes
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login, :first_name, :last_name, :phone_number, :gender, :profession_id, :region_id, :city, :birth_date, :ethnicity_id, :hair_color_id, :eye_color_id, :weight, :height, :waist, :hips, :dress, :shoes, :pants, :neck, :prefered_region_id, :about, :webpage, :courses, :references, :language_ids, :discipline_ids, :gadu_gadu, :bra_id, :bust, :panties, :profile_completed, :achievements, :avatar, :company, :description, :fax_number, :landline_number, :company_name, :street, :postcode, :regon, :nip

  attr_accessor :user_validatable


  # Associations
  belongs_to :profession
  belongs_to :region
  belongs_to :ethnicity
  belongs_to :hair_color
  belongs_to :eye_color
  belongs_to :prefered_region
  belongs_to :bra

  has_many :photos
  has_many :sent_messages, :class_name => "PrivateMessage", :foreign_key => "sender_id"
  has_many :received_messages, :class_name => "PrivateMessage", :foreign_key => "receiver_id"
  has_many :references
  has_many :issued_references, :foreign_key => 'issuer_id', :class_name => "Reference"
  has_many :albums

  has_one :avatar
   
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :disciplines
  has_and_belongs_to_many :availabilities


  # Common validations
  validates_uniqueness_of :login
  validates_length_of :password, :minimum => 6, :on => :create
  validates_presence_of :login

  with_options :if => :user_validatable? do |validatable|
    validatable.validates_length_of :phone_number, :is => 9, :allow_blank => true
    validatable.validates_length_of :first_name, :within => 3..20, :allow_blank => true
    validatable.validates_length_of :last_name, :within => 3..40, :allow_blank => true
    validatable.validates_numericality_of :phone_number, :height, :weight, :waist, :hips, :bust, :shoes, :pants, :neck, :gadu_gadu, :allow_blank => true
    validatable.validates_presence_of :first_name, :last_name, :city, :region, :region_id
  end



  # Profile validations
  with_options :if => [:user_validatable?, :profile?] do |profile|
    profile.validates_presence_of :birth_date, :prefered_region_id
    profile.validates_presence_of :ethnicity, :ethnicity_id, :hair_color, :hair_color_id, :eye_color, :eye_color_id, :weight, :height, :waist, :hips, :dress, :shoes, :unless => Proc.new {|a| a.profession[:type] == 2 }
  end
  validates_presence_of :bust, :bra, :bra_id, :if => [:user_validatable?, :profile?, :female_model?]
  validates_presence_of :pants, :neck, :if => [:user_validatable?, :profile?, :male_model?]
  

  with_options :if => :profile? do |profile|
    profile.validates_presence_of :gender, :profession_id, :profession
  end

  # Company validations
  validates_presence_of :phone_number, :if => [:user_validatable?, :company?, 'landline_number.nil?']
  validates_presence_of :landline_number, :if => [:user_validatable?, :company?, 'phone_number.nil?']
  validates_presence_of :company_name, :street, :postcode, :if => [:user_validatable?, :company?]
  
  # Callbacks
  after_save :update_languages # workaround
  after_update :set_profile_completed

  # Scopes
  scope :completed, where(:profile_completed => true)
  scope :companies, where(:company => true)
  scope :profiles, where(:company.ne => true)

  def self.search(conditions)
    users = User.completed
    users = users.where(:city.in => conditions[:city]) unless conditions[:city].empty?
    users = users.where(:birth_date.lte => Date.today - conditions[:minimum_age].to_i.years) unless conditions[:minimum_age].blank?
    users = users.where(:birth_date.gte => Date.today - conditions[:maximum_age].to_i.years) unless conditions[:maximum_age].blank?
    ['ethnicity','hair_color','eye_color','gender', 'languages', 'disciplines', 'availabilities'].each do |param|
      users = users.where("#{param}_id".to_sym.in => conditions[param.to_sym]) unless conditions[param.to_sym].nil?
    end
    ['region','profession', 'prefered_region'].each do |param|
      users = users.where("#{param}_id".to_sym.in => conditions[param.to_sym]) unless conditions[param.to_sym].blank?
    end
    ['height', 'weight', 'waist', 'hips', 'bust', 'shoes', 'pants', 'neck'].each do |param|
      minimum = "minimum_#{param}".to_sym
      maximum = "maximum_#{param}".to_sym
      users = users.where(param.to_sym.gt => conditions[minimum]) unless conditions[minimum].blank?
      users = users.where(param.to_sym.lt => conditions[maximum]) unless conditions[maximum].blank?
    end
    users
  end
  
  def avatar_url
    (avatar and avatar.image_url) ? avatar.image_url : "no_photo.png"
  end

  def profile?
    not company
  end

  def photos_limit_exceeded?
    photos.count > 4 ? true : false
  end

  def profession_name
    if profession[:type] == 1
      return "Modelka" if gender == 'female'
      return "Model" if gender == 'male'
    end
    profession.name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def gender_string
    return 'Mężczyzna' if gender == 'male'
    return 'Kobieta' if gender == 'female'
  end

  def age
    age = ((Time.now - birth_date.to_time) / 1.year).floor
    post = " lat"
    last = age.to_s[-1]
    post += 'a' if last == '2' or last == '3' or last == '4'
    age.to_s + post
  end

  def height_string
    height.to_s+" cm"
  end

  def weight_string
    weight.to_s+" kg"
  end

  def bust_string
    bust.to_s+" cm"
  end
  
  def waist_string
    waist.to_s+" cm"
  end

  def hips_string
    hips.to_s+" cm"
  end

  def neck_string
    neck.to_s+" cm"
  end

  def pants_string
    pants.to_s+" EU"
  end

  def dress_string
    dress.to_s+" cm"
  end

  def shoes_string
    shoes.to_s+" EU"
  end
    

    
  def female?
    gender == 'female'
  end

  def male?
    gender == 'male'
  end

  def female_model?
    profession[:type] != 2 and gender == 'female' if profession
  end

  def male_model?
    profession[:type] !=2 and gender == 'male' if profession
  end
  
  def user_validatable!
    @validatable = true
  end

  def user_validatable?
    @validatable
  end

  private

  def update_languages
    self.languages.each do |language|
      language.user_ids ||= []
      language.users << self unless language.users.include?(self)
      language.save
    end
  end

  def set_profile_completed
    unless profile_completed
      self.update_attributes :profile_completed => true if valid? and user_validatable?
    end
  end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update, :delete]

  def index
    per_page = 10
    if params[:search_companies]
      @users = User.companies.completed
      @users = @users.where(:region => params[:search_companies][:region]) if params[:region]
      @users = @users.where(:company_name => /#{params[:search_companies][:company_name]}/i) if params[:company_name]
      @users = @users.page(params[:page]).per(per_page)
    else
      @users = params[:search] ? User.profiles.search(params[:search]).page(params[:page]).per(per_page) : User.completed.profiles.page(params[:page]).per(per_page)
    end
  end

  def search
  end

  def search_companies
  end

  def show
    @user = defined?(params[:id]) ? User.find(params[:id]) : current_user
    @photos = @user.photos
    @references = @user.references.accepted
  end

  def edit
    @regions = Region.all
    unless current_user.company?
      @disciplines = Discipline.where(:profession_types => current_user.profession[:type])
      @ethnicities = Ethnicity.all
      @hair_colors = HairColor.all
      @eye_colors = EyeColor.all
      @prefered_regions = PreferedRegion.all
      @languages = Language.all
      @availability_items = Availability.all
      @professions = Profession.all
      @bras = Bra.all
      @height = (140..200).inject({}) {|h, n| h["#{n} cm"] = n; h}
      @weight = (35..120).inject({}) {|h, n| h["#{n} kg"] = n; h}
      @bust = (65..150).inject({}) {|h, n| h["#{n} cm"] = n; h}
      @waist = (50..110).inject({}) {|h, n| h["#{n} cm"] = n; h}
      @hips = (65..150).inject({}) {|h, n| h["#{n} cm"] = n; h}
      @dress = (10..100).inject({}) {|h, n| h["#{n} cm"] = n; h}
      @shoes = (30..48).inject({}) {|h, n| h["#{n} EU"] = n; h}
      @pants = (38..54).inject({}) {|h, n| h["#{n} EU"] = n; h}
      @neck = (18..45).inject({}) {|h, n| h["#{n} cm"] = n; h}
    end
  end

  def update
    edit
    current_user.user_validatable!
    if current_user.update_attributes(params[:user])
      redirect_to edit_user_path, :notice => "Twoje dane zostały zaktualizowne." 
    else
      render :action => 'edit'
    end
  end



  def delete
  end

end

app/views/users/_edit_company_form.html.haml
= semantic_form_for current_user, :html => {:class => 'default-form'} do |f|
  = f.semantic_errors
  = f.inputs :company do
    = f.input :first_name
    = f.input :last_name
    = f.input :phone_number
    = f.input :landline_number
    = f.input :fax_number
    = f.input :webpage
    = f.input :company_name
    = f.input :region, :as => :select, :collection => @regions, :prompt => "wybierz województwo..."
    = f.input :city
    = f.input :street
    = f.input :postcode
    = f.input :nip
    = f.input :regon
    = f.input :description, :as => :text

  = f.buttons do
    = f.commit_button

app/views/users/_edit_profile_form.html.haml
= semantic_form_for current_user, :html => {:class => 'default-form profile-edit'} do |f|
  = f.inputs do
    - unless current_user.profile_completed
      %p
        Wypełnij wszystkie pola oznaczone gwiazdką, aby dokończyć rejestrację.
  = f.semantic_errors
  = f.inputs :contact_data do
    = f.input :first_name, :required => true
    = f.input :last_name, :required => true
    = f.input :phone_number, :required => false
    = f.input :region, :as => :select, :collection => @regions, :prompt => "wybierz województwo...", :required => true
    = f.input :city, :required => true
  = f.inputs :portfolio_and_appearance do
    = f.input :birth_date, :as => :date, :start_year => Time.now.year-10, :end_year => 1900
    - if not current_user.profession.type == 2
      = f.input :ethnicity, :as => :select, :collection => @ethnicities, :prompt => "wybierz pochodzenie..."  
      = f.input :hair_color, :as => :select, :collection => @hair_colors, :prompt => 'wybierz kolor włosów...'
      = f.input :eye_color, :as => :select, :collection => @eye_colors, :prompt => 'wybierz kolor oczu...'
      = f.input :height, :as => :select, :collection => @height
      = f.input :weight, :as => :select, :collection => @weight
      - if current_user.gender == 'female'
        = f.input :bra, :as => :select, :collection => @bras
        = f.input :bust, :collection => @bust
      = f.input :waist, :collection => @waist
      = f.input :hips, :collection => @hips
      = f.input :dress, :collection => @dress
      = f.input :shoes, :collection => @shoes
      - if current_user.gender == 'male'
        = f.input :pants, :collection => @pants
        = f.input :neck, :collection => @neck
    = f.inputs "Zakres pracy" do
      = f.input :disciplines, :as => :check_boxes, :collection => @disciplines
    = f.inputs "Języki" do
      = f.input :languages, :as => :check_boxes, :collection => @languages
    - if current_user.profession.type == 3
      = f.inputs "Dyspozycyjność" do
        = f.input :availability, :as => :check_boxes, :collection => @availability_items

    = f.input :prefered_region, :as => :select, :collection => @prefered_regions, :include_blank => false 

  = f.inputs :others do
    = f.input :webpage
    = f.input :gadu_gadu
    = f.input :skype
    = f.input :courses
    = f.input :achievements
    = f.input :about, :as => :text

  = f.buttons do
    = f.commit_button "Zaakceptuj", :button_html => { :type => "image", :src => asset_path('layout/accept-button.png')}

app/views/users/_photo.html.haml
%li
  - @user.photos.each do |photo|
    = link_to(image_tag(photo.image_url(:thumb), :class => "photo"), photo_path(photo))

app/views/users/_registration_form.html.haml
%p.description
  :markdown
    Rejestracja w serwisie mysenso.pl jest **darmowa**. Dzięki niej otrzymasz szansę na zaprezentowanie swojej twórczości. Serwis udostępnia ci możliwość tworzenia własnego portfolio, wyszukiwania oraz umieszczania ogłoszeń, uczestnictwa w dyskusjach na forum i wiele innych narzędzi, dzięki którym zbliżysz się do świata modelingu.

    **W celu rejestracji uzupełnij poniższy formularz.**
= semantic_form_for(defined?(resource) ? resource : User.new, :as => defined?(resource_name) ? resource_name : User.new, :url => user_registration_path, :html => {:class =>  ["registration-form"]}) do |f|
  = f.semantic_errors if defined?(resource) 
  = f.inputs do
    = f.input :email
    = f.input :password, :hint => "przynajmniej 6 znaków"
    = f.input :password_confirmation
    = f.input :login
    = f.input :company, :as => :boolean, :label => "Konto firmowe"
    #profile-fields{:style => resource.company && "display:none"}
      = f.input :profession_id, :as => :select, :collection => Profession.find(:all), :label => true, :include_blank => false,  :prompt => "wybierz profesję..."
      = f.input :gender, :as => :select, :collection => {"Mężczyzna" => :male, "Kobieta" => :female}, :prompt => "wybierz płeć..."
    = f.commit_button 'Zarejestruj się', :button_html => { :type => "image", :src => asset_path('layout/register-button.png')}

  = render :partial => "devise/shared/links"

app/views/users/_show_profile.html.haml
#content
  .box
    %h2
      = @user.login
      \ - 
      = @user.profession_name

    - if user_signed_in? && current_user != @user
      = link_to 'Wyślij prywatną wiadomość', new_user_private_message_path(@user)
      = link_to 'Zostaw referencję', new_user_reference_path(@user)
    %h3
      = @user.full_name
    %dl
      %dt
        Miejscowość
      %dd= @user.city
      %dt
        Województwo
      %dd= @user.region.name
      - if @user.phone_number
        %dt
          Numer telefonu
        %dd= @user.phone_number
      %dt
        Strona WWW
      %dd= @user.webpage
      %dt
        Wiek
      %dd= @user.age
      - if not @user.profession.type == 2
        %dt
          Pochodzenie etniczne
        %dd= @user.ethnicity.name
        %dt
          Płeć
        %dd= @user.gender_string
        %dt
          Wzrost
        %dd= @user.height_string
        %dt
          Waga
        %dd= @user.weight_string
        - if @user.female?
          %dt
            Biust
          %dd= @user.bust_string
        %dt
          Talia
        %dd= @user.waist_string
        %dt
          Biodra
        %dd= @user.hips_string
        - if @user.male?
          %dt
            Kołnierzyk
          %dd= @user.neck_string
          %dt
            Spodnie
          %dd= @user.pants_string
        %dt 
          Kolor włosów
        %dd= @user.hair_color.name
        %dt
          Kolor oczu
        %dd= @user.eye_color.name
        %dt
          Ubranie
        %dd= @user.dress_string
        %dt
          Obuwie
        %dd= @user.shoes_string
        - if @user.female?
          %dt
            Biustonosz
      %dt
        Preferowany region pracy
      %dd= @user.prefered_region.name

    #about
      %h2
        O sobie
      = @user.about
    #courses
      %h2
        Odbyte kursy/szkolenia
      = @user.courses

    - unless @references.empty?
      #references
        %h2
          Referencje
        - @references.each do |reference|
          = reference.content
        
        

      - unless @photos.empty?
        %h3
        Lista zdjęć
      %ul
        = render @photos

app/views/users/_user.html.haml
.user
  = link_to user.login, user_path(user)
  = link_to (image_tag user.avatar ? user.avatar.image_url.to_s : ''), user_path(user.id)

app/views/users/delete.html.haml
%h1 Users#delete
%p Find me in app/views/users/delete.html.haml

app/views/users/edit.html.haml
- content_for :title, "Edytuj swoje dane"
- if current_user.company?
  = render :partial => 'edit_company_form'
- else
  = render :partial => 'edit_profile_form'

app/views/users/index.html.haml
%h2 Lista użytkowników

= render @users
= paginate @users 

app/views/users/search.html.haml
%h2
  Wyszukaj użytkowników

= semantic_form_for :search, :url => users_path do |f|
  = f.inputs do
    = f.input :profession, :as => :select, :collection => Profession.all, :required => false, :label => "Profesja"
    = f.input :gender, :as => :radio, :collection => {"Mężczyzna" => :male, "Kobieta" => :female}, :required => false, :label => 'Płeć'
    = f.input :city, :required => false, :label => 'Miejscowość'
    = f.input :region, :as => :select, :collection => Region.all, :required => false, :label => 'Województwo'
    = f.inputs "Wiek" do
      = f.input :minimum_age, :label => 'od', :required => false
      = f.input :maximum_age, :label => 'do', :required => false
  = f.inputs "Informacje i wymiary" do
    = f.input :ethnicity, :as => :select, :collection => Ethnicity.all, :multiple => true, :include_blank => false, :required => false, :label => "Pochodzenie etniczne"
    = f.input :hair_color, :as => :select, :collection => HairColor.all, :multiple => true, :include_blank => false, :required => false, :label => "Kolor włosów"
    = f.input :eye_color, :as => :select, :collection => EyeColor.all, :multiple => true, :include_blank => false, :required => false, :label => "Kolor oczu"
    = f.inputs "Wzrost" do
      = f.input :minimum_height, :label => 'od', :required => false
      = f.input :maximum_height, :label => 'do', :required => false
    = f.inputs "Waga" do
      = f.input :minimum_weight, :label => 'od', :required => false
      = f.input :maximum_weight, :label => 'do', :required => false
    = f.inputs "Biust" do
      = f.input :minimum_bust, :label => 'od', :required => false
      = f.input :maximum_bust, :label => 'do', :required => false
    = f.inputs "Talia" do
      = f.input :minimum_waist, :label => 'od', :required => false
      = f.input :maximum_waist, :label => 'do', :required => false
    = f.inputs "Biodra" do
      = f.input :minimum_hips, :label => 'od', :required => false
      = f.input :maximum_hips, :label => 'do', :required => false
    = f.inputs "Obuwie" do
      = f.input :minimum_shoes, :label => 'od', :required => false
      = f.input :maximum_shoes, :label => 'do', :required => false
    = f.inputs "Spodnie" do
      = f.input :minimum_pants, :label => 'od', :required => false
      = f.input :maximum_pants, :label => 'do', :required => false
    = f.inputs "Kołnierzyk" do
      = f.input :minimum_neck, :label => 'od', :required => false
      = f.input :maximum_neck, :label => 'do', :required => false
    = f.input :disciplines, :as => :select, :multiple => true, :label => 'Zakres wykonywanych prac', :required => false, :collection => Discipline.all, :include_blank => false
    = f.input :prefered_region, :as => :select, :label => 'Preferowany region pracy', :required => false, :collection => PreferedRegion.all
    = f.input :languages, :as => :select, :multiple => true, :label => 'Języki', :required => false, :collection => Language.all, :include_blank => false
    = f.input :availabilities, :as => :select, :multiple => true, :label => "Dyspozycyjność", :required => false, :collection => Availability.all, :include_blank => false
  = f.buttons do  
    = f.submit "Wyszukaj"

app/views/users/search_companies.html.haml
%h2
  Wyszukaj agencje

= semantic_form_for :search_companies, :url => users_path do |f|
  = f.inputs do
    = f.input :region, :as => :select, :collection => Region.all, :prompt => "wybierz województwo..."
    = f.input :company_name
  = f.buttons

app/views/users/show.html.haml
= render :partial => "layouts/edit_user_sidebar", :if => user_signed_in?

= render :partial => "show_profile", :object => @user if @user.profile?
= render :partial => "show_company", :object => @user if @user.company?

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml