config/routes.rb
# -*- encoding : utf-8 -*-
Mysenso::Application.routes.draw do

  resource :user do
    resource :avatar do
      collection do
        get 'index'
        put 'update_crop'
      end
    end
  end

  resources :references, :only => [:destroy] do
    collection do
      get 'index'
    end
    member do
      put 'accept'
    end
  end

  resources :private_messages, :except => [:edit, :update] do
 
    collection do
      get 'received' => 'private_messages#index'
      get 'sent' => 'private_messages#index', :defaults => { :type => :sent }
      post 'destroy_multiple'
      post 'mark_as_read_multiple'
    end
    
  end

  resources :avatars

  resources :albums do
    resources :photos
    
    collection do
      get 'manage'
    end
    
    member do
      get 'manage', :action => 'manage_photos'
    end
  end

  devise_for :user, :path_prefix => 'd' do
    root :to => "home#index"
  end

  resources :users, :except => [:update, :show] do
    collection do
      get 'search'
      get 'search_companies'
      post 'index'
    end
    resource :private_message, :only => [:new]
    resources :references, :only => [:new, :create]
    resources :albums, :only => [:index]
  end
  get '/users/:id' => 'users#show', :as => 'user'
  put '/users/:id' => 'users#update', :as => 'user'

  root :to => "home#index"

end

app/models/private_message.rb
# -*- encoding : utf-8 -*-
class PrivateMessage
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :content
  field :read, :type => Boolean, :default => false

  scope :unread, where(:read => false)

  belongs_to :sender, :class_name => "User"
  belongs_to :receiver, :class_name => "User"

  validates_presence_of :title, :content, :sender_id, :receiver_id

  def read!
    self.update_attributes :read => true unless read == true
  end

  def unread?
    not self.read
  end
  
  def reply_title
    "Re: "+title
  end
end

app/controllers/private_messages_controller.rb
# -*- encoding : utf-8 -*-
class PrivateMessagesController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    per_page = 5
    if params[:type] == :sent
      @messages = current_user.sent_messages.order_by([:created_at, :desc]).page(params[:page]).per(per_page)
    else
      @messages = current_user.received_messages.order_by([:created_at, :desc]).page(params[:page]).per(per_page)
    end
  end

  def show
    @message = PrivateMessage.find(params[:id])
    @message.read! if @message.receiver == current_user
    @reply = PrivateMessage.new 
  end

  def new
    @message = PrivateMessage.new
  end

  def create
    @message = PrivateMessage.new params[:private_message]
    @message.sender = current_user
    if @message.save
      redirect_to user_path(@message.receiver), :notice => "Wiadomość została wysłana"
    else
      render :new
    end
  end
  
  def destroy_multiple
    unless params[:private_message_ids].nil?
      messages = PrivateMessage.where(:_id.in => params[:private_message_ids])
      messages.each {|m| m.destroy if m.receiver == current_user}
    end
    redirect_to private_messages_path
  end
  
  def mark_as_read_multiple
    unless params[:private_message_ids].nil?
      messages = PrivateMessage.where(:_id.in => params[:private_message_ids])
      messages.each {|m| m.read! if m.receiver == current_user}
    end
    redirect_to private_messages_path
  end
  
  def destroy
    @message = PrivateMessage.find(params[:id])
    if @message.receiver == current_user and @message.destroy
      redirect_to private_messages_path, :notice => "Wiadomość została usunięta"
    else
      redirect_to private_messages_path, :error => "Wiadomość nie została usunięta"
    end
  end

end

app/views/private_messages/_private_message.html.haml
%tr{:class => ["row",("unread" if private_message.unread?)]}
  %td
    = (check_box_tag 'private_message_ids[]', private_message.id) if private_message.receiver == current_user
  %td
    = image_tag private_message.sender.avatar_url, :alt => "Avatar", :class => :avatar
  %td
    = link_to private_message.sender.full_name, user_path(private_message.sender)
    %br/
    %span
      = private_message.created_at.strftime("%d.%m.%Y %H:%M")
  %td
    = link_to(private_message.title, private_message_path(private_message))
    %br/
    %span
      = truncate(private_message.content, :length => 50)
  %td
    = link_to(image_tag("layout/pm-remove.png"), private_message_path(private_message), :confirm => "Jesteś pewny?", :method => :delete)
    
  
  

app/views/private_messages/index.html.haml
- content_for :title, "Twoje prywatne wiadomości"

#private-messages
  = form_tag destroy_multiple_private_messages_path, :method => :post do
    %fieldset
      %table.private-messages
        %tr.menu
          %td{:colspan => 3}
            %ul
              %li{:class => ("selected" if params[:type] != :sent)}
                = link_to 'Odebrane', received_private_messages_path()
              %li{:class => ("selected" if params[:type] == :sent)}
                = link_to 'Wysłane', sent_private_messages_path()
          %td{:colspan => 2}
            Czynności: 
            = select_tag :action_select, options_for_select([['wybierz...'], ['usuń zaznaczone', 'remove_selected'], ['oznacz jako przeczytane', 'mark_as_read']])
        %tr.head
          %td{:colspan => 2}
            = (check_box_tag "check_all", '1', false, :class => "checkall")
          %td
            Nadawca / Data
          %td
            Temat / Treść
          %td
            = paginate @messages

        = render @messages

app/views/private_messages/new.html.haml
%h2
  Wyślij prywatną wiadomość
= semantic_form_for @message do |f|
  = f.input :title
  = f.input :content, :as => :text
  = f.hidden_field :receiver, :value => params[:user_id]
  = f.buttons

app/views/private_messages/received.html.haml
- content_for :title, "Twoje prywatne wiadomości"

#private-messages
  = render :partial => 'private_messages', :object => @received_messages


app/views/private_messages/sent.html.haml
- content_for :title, "Twoje prywatne wiadomości"

#private-messages
  = render :partial => 'private_messages', :object => @sent_messages



app/views/private_messages/show.html.haml
- content_for :title, "Twoje prywatne wiadomości"

#private-message
  .head
    = link_to "powrót do odebranych", private_messages_path
    .date
      = @message.created_at.strftime("%d.%m.%Y %H:%M")
  .avatar
    = image_tag @message.sender.avatar_url, :alt => "Avatar", :class => :avatar
    .name
      = link_to @message.sender.full_name, user_path(@message.sender)
    = link_to(image_tag("layout/pm-remove.png"), private_message_path(@message), :confirm => "Jesteś pewny?", :method => :delete, :class => :delete)

  %h3= @message.title
  .content= @message.content

  .reply
    = semantic_form_for @reply, :html => {:class => "default-form"} do |f|
      = f.hidden_field :receiver, :value => @message.receiver_id
      = f.hidden_field :title, :value => @message.reply_title
      = f.inputs do
        = f.input :content, :as => :text, :label => "Odpowiedź"
        = f.submit