config/routes.rb
# -*- encoding : utf-8 -*-
Mysenso::Application.routes.draw do

  resource :user do
    resource :avatar do
      collection do
        get 'index'
        put 'update_crop'
      end
    end
  end

  resources :references, :only => [:destroy] do
    collection do
      get 'index'
    end
    member do
      put 'accept'
    end
  end

  resources :private_messages, :except => [:edit, :update] do
 
    collection do
      get 'received' => 'private_messages#index'
      get 'sent' => 'private_messages#index', :defaults => { :type => :sent }
      post 'destroy_multiple'
      post 'mark_as_read_multiple'
    end
    
  end

  resources :avatars

  resources :albums do
    resources :photos
    
    collection do
      get 'manage'
    end
    
    member do
      get 'manage', :action => 'manage_photos'
    end
  end

  devise_for :user, :path_prefix => 'd' do
    root :to => "home#index"
  end

  resources :users, :except => [:update, :show] do
    collection do
      get 'search'
      get 'search_companies'
      post 'index'
    end
    resource :private_message, :only => [:new]
    resources :references, :only => [:new, :create]
    resources :albums, :only => [:index]
  end
  get '/users/:id' => 'users#show', :as => 'user'
  put '/users/:id' => 'users#update', :as => 'user'

  root :to => "home#index"

end

app/models/reference.rb
# -*- encoding : utf-8 -*-
class Reference
  include Mongoid::Document

  field :content
  field :accepted, :type => Boolean, :default => false

  scope :unaccepted, where(:accepted => false)
  scope :accepted, where(:accepted => true)

  belongs_to :user
  belongs_to :issuer, :class_name => "User"
end

app/controllers/references_controller.rb
# -*- encoding : utf-8 -*-
class ReferencesController < ApplicationController
  before_filter :authenticate_user!  

  def index
    @references = current_user.references
  end

  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @reference = @user.references.build(params[:reference])
    @reference.issuer = current_user
    if @reference.save
      redirect_to user_path(@user), :notice => "Referencja została wystawiona, zaczekaj na akceptację użytkownika"
    else
      render :action => :new
    end
  end

  def accept
    @reference = Reference.find(params[:id])
    if @reference.update_attributes(:accepted => true)
      redirect_to references_path, :notice => "Referencja została zaakceptowana, znajdziesz ją w swoim profilu" and return
    else
      redirect_to references_path, :error => "Wystąpił błąd podczas akceptacji referencji, spróbuj ponownie później"
    end
  end

end

app/views/references/index.html.haml
= render :partial => 'layouts/edit_user_sidebar'

#edit-user-content
  .box
    %h2
      Twoje referencje

    - unless @references.unaccepted.empty?
      %h3
        Do akceptacji
      %ul
        - @references.unaccepted.each do |reference|
          %li
            = reference.content
            = link_to "Akceptuj", accept_reference_path(reference), :method => :put
            = link_to "Usuń", reference_path(reference), :method => :delete
          

    %h3
      Wystawione Tobie

app/views/references/new.html.haml
%h2
  Zostaw referencję użytkownikowi
  = @user.login

= semantic_form_for [@user,@user.references.build] do |f|
  = f.input :content
  = f.buttons