config/routes.rb
# -*- encoding : utf-8 -*-
Mysenso::Application.routes.draw do

  resource :user do
    resource :avatar do
      collection do
        get 'index'
        put 'update_crop'
      end
    end
  end

  resources :references, :only => [:destroy] do
    collection do
      get 'index'
    end
    member do
      put 'accept'
    end
  end

  resources :private_messages, :except => [:edit, :update] do
 
    collection do
      get 'received' => 'private_messages#index'
      get 'sent' => 'private_messages#index', :defaults => { :type => :sent }
      post 'destroy_multiple'
      post 'mark_as_read_multiple'
    end
    
  end

  resources :avatars

  resources :albums do
    resources :photos
    
    collection do
      get 'manage'
    end
    
    member do
      get 'manage', :action => 'manage_photos'
    end
  end

  devise_for :user, :path_prefix => 'd' do
    root :to => "home#index"
  end

  resources :users, :except => [:update, :show] do
    collection do
      get 'search'
      get 'search_companies'
      post 'index'
    end
    resource :private_message, :only => [:new]
    resources :references, :only => [:new, :create]
    resources :albums, :only => [:index]
  end
  get '/users/:id' => 'users#show', :as => 'user'
  put '/users/:id' => 'users#update', :as => 'user'

  root :to => "home#index"

end

app/views/layouts/_edit_user_sidebar.html.haml
#sidebar.edit_user
  .box
    %h2 Zarządzaj profilem
    .padding
      .avatar
        = image_tag current_user.avatar_url, :alt => "Avatar", :class => :avatar
        .name
          = current_user.first_name ? link_to(current_user.full_name, user_path(current_user)) : 'Nieznajomy' 

      %ul.menu
        %li= link_to(current_user.received_messages.unread.empty? ? 'Wiadomości' : "Nowe wiadomości: #{current_user.received_messages.unread.count}", private_messages_path)
        %li= link_to "Galeria zdjęć", manage_albums_path
        %li= link_to "Edycja awataru", user_avatar_path
        %li= link_to "Edycja danych", edit_user_path
        -unless current_user.company?
          %li= link_to(current_user.references.unaccepted.empty? ? 'Referencje' : "Nowe referencje: #{current_user.references.unaccepted.count}", references_path) 
        %li= link_to "Wyloguj się", destroy_user_session_path

app/views/layouts/_top_navigation.html.haml
#top-navigation
  - if user_signed_in? 
    Witaj, 
    = current_user.first_name ? link_to(current_user.first_name, user_path(current_user)) : 'nieznajomy' 
    = "(#{current_user.email})"
    = link_to('Wyloguj się', destroy_user_session_path, :method => :delete)

  - if not user_signed_in?
    = link_to 'Logowanie', '#login-box', :id => "login-trigger"
    = link_to 'Rejestracja', new_registration_path(:user)
    #login-box
      %h2
        Zaloguj się
      = link_to image_tag("layout/modal-close.png"), "#", :class => 'close'
      = semantic_form_for User.new, :url => user_session_path do |f|
        = f.inputs do
          = f.input :email, :label => 'E-mail: '
          = f.input :password, :label => 'Hasło: '
        = f.buttons do
          = f.input :remember_me, :as => :boolean, :label => 'Zapamiętaj mnie', :wrapper_html => {:class => 'remember-me'}
          = f.commit_button 'Zaloguj się', :button_html => { :type => "image", :src => asset_path('layout/login-button.png')}
        = render :partial => 'devise/shared/links', :locals => {:modal_box => 'login'}


app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mysenso
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    /[if IE 6]
      = stylesheet_link_tag 'formtastic_ie6'
    /[if IE 7]
      = stylesheet_link_tag 'formtastic_ie7'
    = csrf_meta_tag
  %body.mysenso.bp
    #container
      #header
        = render :partial => 'layouts/top_navigation'
        = render :partial => 'layouts/main_navigation'
      #wrapper
        .padding
          - if notice
            %p.notice
              = notice
          - if alert
            %p.alert
              = alert
          = render :partial => 'layouts/edit_user_sidebar' if user_signed_in?
          #content{:class => user_signed_in? ? '' : 'wide'}
            .box
              %h2= yield :title 
              .padding
                = yield
      #footer
        Copyright Lucjan Suski